# Generated by Django 3.2 on 2022-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
