# Generated by Django 3.2 on 2022-01-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
