# Generated by Django 3.2 on 2022-01-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
