# Generated by Django 3.2 on 2022-01-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
